Repository youcan-shop/youcan-ui, pull requests merged in 2024-01, with the labels that each got.

#206 DARK: fix ResourcePicker resources reactive bug
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/ResourcePicker/ResourcePicker.vue
Labels: 💻 Ready for review

#204 DARK: improve resource picker styles
  packages/vue3/src/components/ResourcePicker/Internal/Resource.vue
  packages/vue3/src/components/ResourcePicker/ResourcePicker.vue
Labels: 💻 Ready for review

#207 DARK: add check to disable add button if no resources are selected
  packages/vue3/src/components/ResourcePicker/ResourcePicker.vue
Labels: ✅ Reviewed

#203 YSHOP2-1217: Add fixes based on Feedback meeting
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/Dropdown/Dropdown.vue
  packages/vue3/src/components/Dropdown/DropdownList.vue
  packages/vue3/src/components/Dropdown/Internal/DropdownItem.vue
  packages/vue3/src/components/Dropdown/MultiselectDropdown.vue
  packages/vue3/src/components/Dropdown/helpers.ts
Labels: 💻 Ready for review

#200 YSHOP2-1221: Added thickness prop to divider
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/Divider/Divider.vue
  packages/vue3/src/components/Divider/types.ts
Labels: ✅ Reviewed

#208 DARK: add searchPlaceholder as prop
  packages/vue3/src/components/ResourcePicker/ResourcePicker.vue
  packages/vue3/src/components/ResourcePicker/types.ts
Labels: 💻 Ready for review, ✅ Reviewed

#198 YSHOP2-1213: Fixed divider vertical orientation
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/Divider/Divider.vue
Labels: ✅ Reviewed

#199 YSHOP2-1214: Added margin to the divider
  packages/vue3/src/components/Divider/Divider.vue
Labels: ✅ Reviewed

#186 YSHOP2-1137: RichText > Added missing features and fixed bugs
  packages/vue3/package.json
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/RichText/RichText.vue
  packages/vue3/src/components/RichText/extensions/indent.ts
  packages/vue3/src/components/RichText/handleDrop.ts
  packages/vue3/src/components/RichText/internal/CodeBlock.vue
  packages/vue3/src/components/RichText/internal/Colors/Color.vue
  packages/vue3/src/components/RichText/internal/Colors/swatches.ts
  packages/vue3/src/components/RichText/internal/Emojis/EmojiPicker.vue
  packages/vue3/src/components/RichText/internal/Emojis/emojis.ts
  packages/vue3/src/components/RichText/internal/SpecialCharacters/CharacterPicker.vue
  packages/vue3/src/components/RichText/internal/SpecialCharacters/specialCharacters.ts
  packages/vue3/src/components/RichText/internal/Table.vue
  packages/vue3/src/components/RichText/internal/Tooltip.vue
  packages/vue3/src/components/RichText/internal/utils.ts
  packages/vue3/src/components/RichText/toolbar.ts
  packages/vue3/tiptap.d.ts
  packages/vue3/tsconfig.json
  pnpm-lock.yaml
Labels: ✅ Reviewed

#209 Revert "YSHOP2-1137: RichText > Added missing features and fixed bugs"
  packages/vue3/package.json
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/RichText/RichText.vue
  packages/vue3/src/components/RichText/extensions/indent.ts
  packages/vue3/src/components/RichText/handleDrop.ts
  packages/vue3/src/components/RichText/internal/CodeBlock.vue
  packages/vue3/src/components/RichText/internal/Color.vue
  packages/vue3/src/components/RichText/internal/EmojiPicker.vue
  packages/vue3/src/components/RichText/internal/SpecialCharacters/CharacterPicker.vue
  packages/vue3/src/components/RichText/internal/SpecialCharacters/specialCharacters.ts
  packages/vue3/src/components/RichText/internal/Table.vue
  packages/vue3/src/components/RichText/internal/Tooltip.vue
  packages/vue3/src/components/RichText/internal/emojis.ts
  packages/vue3/src/components/RichText/internal/swatches.ts
  packages/vue3/src/components/RichText/internal/utils.ts
  packages/vue3/src/components/RichText/toolbar.ts
  packages/vue3/tiptap.d.ts
  packages/vue3/tsconfig.json
  pnpm-lock.yaml
Labels: ✅ Reviewed

#211 DARK: dark-make-resourcePicker-variants-POJOs
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/ResourcePicker/ResourcePicker.vue
Labels: 💻 Ready for review

#212 YSHOP2-1237: Added new icons
  packages/icons/info.json
  packages/icons/source/arrow-u-right-down.svg
  packages/icons/source/arrows-out-simple.svg
  packages/icons/source/chat.svg
  packages/icons/source/info-1.svg
  packages/icons/source/plugs-connected.svg
  packages/icons/source/plugs.svg
  packages/icons/source/rocket-launch.svg
  packages/icons/source/truck.svg
  packages/vue3/src/_dev/App.vue
Labels: ✅ Reviewed

#213 YSHOP2-1239: Dropdown > Add scroll-based pagination
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/Dropdown/Dropdown.vue
  packages/vue3/src/components/Dropdown/DropdownList.vue
  packages/vue3/src/components/Dropdown/MultiselectDropdown.vue
  packages/vue3/src/components/Spinner/Spinner.vue
Labels: 💻 Ready for review

#214 YSHOP2-1247: Input > Add Show/Hide if Input type is password
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/Input/Input.vue
Labels: ✅ Reviewed

#215 Update CONTRIBUTING.md to include step to run build
  CONTRIBUTING.md
Labels: ✅ Reviewed

#217 DARK: remove code component
  packages/vue3/package.json
  packages/vue3/src/components/Code/Code.vue
  packages/vue3/src/components/Code/languages/index.ts
  packages/vue3/src/components/Code/themes/dark.css
  packages/vue3/src/components/Code/themes/line-numbers.css
  packages/vue3/src/components/Code/types.ts
  packages/vue3/src/components/index.ts
Labels: 💻 Ready for review

#218 Added custom props type for alert-badge-checkbox
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/Alert/Alert.vue
  packages/vue3/src/components/Alert/types.ts
  packages/vue3/src/components/Badge/Badge.vue
  packages/vue3/src/components/Badge/types.ts
  packages/vue3/src/components/Checkbox/Checkbox.vue
  packages/vue3/src/components/Checkbox/types.ts
Labels: 💻 Ready for review

#219 Added custom type for buttons props
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/Button/PrimaryButton.vue
  packages/vue3/src/components/Button/PrimaryDestructiveButton.vue
  packages/vue3/src/components/Button/SecondaryButton.vue
  packages/vue3/src/components/Button/SecondaryDestructiveButton.vue
  packages/vue3/src/components/Button/TertiaryButton.vue
  packages/vue3/src/components/Button/_BaseButton.vue
  packages/vue3/src/components/Button/types.ts
Labels: ✅ Reviewed

#220 Added custom props for color component
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/Color/ColorInput.vue
  packages/vue3/src/components/Color/ColorPicker.vue
  packages/vue3/src/components/Color/Internal/Alpha.vue
  packages/vue3/src/components/Color/Internal/Backdrop.vue
  packages/vue3/src/components/Color/Internal/Hue.vue
  packages/vue3/src/components/Color/Internal/Override.vue
  packages/vue3/src/components/Color/Internal/Saturation.vue
  packages/vue3/src/components/Color/Internal/Swatches.vue
  packages/vue3/src/components/Color/Internal/types.ts
  packages/vue3/src/components/Color/types.ts
Labels: ✅ Reviewed

#221 Added custom props for divider and dateInput
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/DateInput/DateInput.vue
  packages/vue3/src/components/DateInput/DatePicker.vue
  packages/vue3/src/components/DateInput/Internal/Day.vue
  packages/vue3/src/components/DateInput/Internal/MonthSwitcher.vue
  packages/vue3/src/components/DateInput/Internal/types.ts
  packages/vue3/src/components/DateInput/types.ts
  packages/vue3/src/components/Divider/Divider.vue
  packages/vue3/src/components/Divider/types.ts
Labels: ✅ Reviewed

#222 Added custom types for components props
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/Draggable/Draggable.vue
  packages/vue3/src/components/Draggable/DraggableItem.vue
  packages/vue3/src/components/Draggable/types.ts
  packages/vue3/src/components/Dropdown/Dropdown.vue
  packages/vue3/src/components/Dropdown/DropdownList.vue
  packages/vue3/src/components/Dropdown/Internal/DropdownItem.vue
  packages/vue3/src/components/Dropdown/MultiselectDropdown.vue
  packages/vue3/src/components/Dropdown/types.ts
Labels: ✅ Reviewed

#223 Added custom types for increment input loading props
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/Increment/Increment.vue
  packages/vue3/src/components/Increment/types.ts
  packages/vue3/src/components/Input/Input.vue
  packages/vue3/src/components/Input/prefixes/DropdownPrefix.vue
  packages/vue3/src/components/Input/types.ts
  packages/vue3/src/components/Loading/Loading.vue
  packages/vue3/src/components/Loading/types.ts
Labels: ✅ Reviewed

#224 Added custom types for modal multiswitch and pagination bar props
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/Modal/Modal.vue
  packages/vue3/src/components/Modal/types.ts
  packages/vue3/src/components/MultiSwitch/MultiSwitch.vue
  packages/vue3/src/components/MultiSwitch/SwitchButton.vue
  packages/vue3/src/components/MultiSwitch/types.ts
  packages/vue3/src/components/PaginationBar/Internal/NavigationButton.vue
  packages/vue3/src/components/PaginationBar/PaginationBar.vue
  packages/vue3/src/components/PaginationBar/types.ts
Labels: ✅ Reviewed

#226 Added custom types for radioList rating and search props
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/RadioList/RadioList.vue
  packages/vue3/src/components/RadioList/types.ts
  packages/vue3/src/components/Rating/Rating.vue
  packages/vue3/src/components/Rating/RatingInput.vue
  packages/vue3/src/components/Rating/types.ts
  packages/vue3/src/components/Search/Internal/SearchResult.vue
  packages/vue3/src/components/Search/SearchInput.vue
  packages/vue3/src/components/Search/types.ts
Labels: ✅ Reviewed

#227 Added custom types for SettingsNav Sidebar and Skeleton props
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/SettingsNav/SettingsNavItem.vue
  packages/vue3/src/components/SettingsNav/types.ts
  packages/vue3/src/components/Sidebar/Sidebar.vue
  packages/vue3/src/components/Sidebar/SidebarItem.vue
  packages/vue3/src/components/Sidebar/SidebarSubitem.vue
  packages/vue3/src/components/Sidebar/types.ts
  packages/vue3/src/components/Skeleton/Skeleton.vue
  packages/vue3/src/components/Skeleton/types.ts
Labels: ✅ Reviewed

#228 Added custom types for slider spinner and status props
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/Slider/Slider.vue
  packages/vue3/src/components/Slider/types.ts
  packages/vue3/src/components/Spinner/Spinner.vue
  packages/vue3/src/components/Spinner/types.ts
  packages/vue3/src/components/Status/EditableStatus.vue
  packages/vue3/src/components/Status/StaticStatus.vue
  packages/vue3/src/components/Status/types.ts
Labels: ✅ Reviewed

#229 Added custom types for table and tag props
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/Table/Internal/Button.vue
  packages/vue3/src/components/Table/Internal/Link.vue
  packages/vue3/src/components/Table/Internal/TableRow.vue
  packages/vue3/src/components/Table/Internal/types.ts
  packages/vue3/src/components/Table/Table.vue
  packages/vue3/src/components/Table/types.ts
  packages/vue3/src/components/Tag/Tag.vue
  packages/vue3/src/components/Tag/TagItem.vue
  packages/vue3/src/components/Tag/types.ts
Labels: ✅ Reviewed

#230 Added custom types for tabs textarea and thumbnail props
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/Tabs/Tab.vue
  packages/vue3/src/components/Tabs/types.ts
  packages/vue3/src/components/TextArea/TextArea.vue
  packages/vue3/src/components/TextArea/types.ts
  packages/vue3/src/components/Thumbnail/Thumbnail.vue
  packages/vue3/src/components/Thumbnail/types.ts
Labels: ✅ Reviewed

#231 Added custom types for toast toggle and tooltip props
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/Toast/Toast.vue
  packages/vue3/src/components/Toast/types.ts
  packages/vue3/src/components/Toggle/Toggle.vue
  packages/vue3/src/components/Toggle/types.ts
  packages/vue3/src/components/Tooltip/Tooltip.vue
  packages/vue3/src/components/Tooltip/types.ts
Labels: ✅ Reviewed

#234 YSHOP2-1259: Table > Add ellipsis to cell text
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/Table/Internal/TableRow.vue
Labels: ✅ Reviewed

#235 github workflows
  .github/workflows/lint.yaml
  packages/eslint-plugin-youcan/src/index.ts
  packages/eslint-plugin-youcan/src/rules/generic-spacing.ts
  packages/eslint-plugin-youcan/src/rules/if-newline.ts
  packages/eslint-plugin-youcan/src/rules/import-dedupe.ts
  packages/eslint-plugin-youcan/src/rules/prefer-inline-type-import.ts
  packages/eslint-plugin-youcan/src/utils.ts
  packages/eslint-plugin-youcan/tsconfig.json
  packages/vue3/src/components/Checkbox/Checkbox.stories.ts
  packages/vue3/src/components/DateInput/DateInput.stories.ts
  packages/vue3/src/components/Increment/Increment.stories.ts
  packages/vue3/src/components/PaginationBar/PaginationBar.stories.ts
  packages/vue3/src/components/RichText/RichText.vue
  packages/vue3/src/components/RichText/extensions/textstyle.ts
  packages/vue3/src/components/RichText/handleDrop.ts
  packages/vue3/src/components/RichText/toolbar.ts
  packages/vue3/src/components/Toggle/Toggle.stories.ts
  pnpm-lock.yaml
Labels: 💻 Ready for review

#238 YSHOP2-1274: Remove code component
  packages/vue3/package.json
  packages/vue3/src/components/Code/Code.vue
  packages/vue3/src/components/Code/languages/index.ts
  packages/vue3/src/components/Code/themes/dark.css
  packages/vue3/src/components/Code/themes/line-numbers.css
  packages/vue3/src/components/Code/types.ts
  packages/vue3/src/components/index.ts
  pnpm-lock.yaml
Labels: 💻 Ready for review

#239 YSHOP2-1275: Dropdwon > background color issue
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/Dropdown/DropdownList.vue
  packages/vue3/src/components/Input/Input.vue
  packages/vue3/src/components/Input/types.ts
  packages/vue3/src/components/TextArea/TextArea.vue
Labels: 💻 Ready for review

#240 Dark fix toast
  package.json
  packages/core/package.json
  packages/eslint-all/package.json
  packages/eslint-basic/package.json
  packages/eslint-plugin-youcan/package.json
  packages/eslint-typescript/package.json
  packages/eslint-vue/package.json
  packages/icons/package.json
  packages/visuals/package.json
  packages/vue3/package.json
  packages/vue3/src/components/ToastContainer/ToastContainer.vue
Labels: ✅ Reviewed

#243 YSHOP2-1289: Added new icons for RichText editor
  packages/icons/info.json
  packages/icons/source/cell-style.svg
  packages/icons/source/cell.svg
  packages/icons/source/column.svg
  packages/icons/source/corners-in.svg
  packages/icons/source/image-legend.svg
  packages/icons/source/image-position.svg
  packages/icons/source/open-link.svg
  packages/icons/source/row.svg
  packages/icons/source/table-footer.svg
  packages/icons/source/table-header.svg
  packages/icons/source/table-style.svg
  packages/icons/source/text-alt.svg
  packages/icons/source/vertical-align.svg
  packages/vue3/src/_dev/App.vue
Labels: ✅ Reviewed

#247 UploadedMedia > image preview by url
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/Thumbnail/types.ts
  packages/vue3/src/components/Upload/UploadedMedia.vue
  packages/vue3/src/components/Upload/types.ts
Labels: 💻 Ready for review

#250 DARK fix uploadedFile props type lint error
  packages/vue3/src/components/Upload/UploadedFile.vue
  packages/vue3/src/components/Upload/UploadedMedia.vue
  packages/vue3/src/components/Upload/types.ts
Labels: 💻 Ready for review

#249 YSHOP2-1294: Update storybook
  packages/vue3/.storybook/main.ts
  packages/vue3/package.json
  packages/vue3/src/components/Alert/Alert.stories.ts
  pnpm-lock.yaml
Labels: ✅ Reviewed

#242 YSHOP2-1244: Added benchmarking config for building vue3 package
  bench.config.mjs
  package.json
  packages/vue3/package.json
  packages/vue3/vue3.bench.mjs
  pnpm-lock.yaml
Labels: ✅ Reviewed

#251 YSHOP2-1241: Upgraded vue and vite versions
  packages/vue3/package.json
  pnpm-lock.yaml
Labels: ✅ Reviewed

#248 Add Drawer component
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/Drawer/Drawer.vue
  packages/vue3/src/components/Drawer/types.ts
  packages/vue3/src/components/Modal/Modal.vue
  packages/vue3/src/components/Overlay/Overlay.vue
  packages/vue3/src/components/index.ts
Labels: ✅ Reviewed

#245 YSHOP2-1216: Added DropdownMenu component
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/DropdownMenu/DropdownMenu.vue
  packages/vue3/src/components/DropdownMenu/DropdownMenuItem.vue
  packages/vue3/src/components/DropdownMenu/types.ts
  packages/vue3/src/components/index.ts
Labels: ⏳ in progress

#252 YSHOP2-1297: Dropdown > Doesn't have an error state
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/Dropdown/Dropdown.vue
  packages/vue3/src/components/Dropdown/MultiselectDropdown.vue
  packages/vue3/src/components/Dropdown/types.ts
Labels: 💻 Ready for review

#254 Dark: Fixed import error
  packages/vue3/src/components/DropdownMenu/DropdownMenuItem.vue
Labels: 💻 Ready for review

#241 YSHOP2-1276: Exported components types
  packages/vue3/package.json
  packages/vue3/src/types/index.ts
Labels: ⏳ in progress

#253 YSHOP2-1312: Create new folder to define helpers
  packages/vue3/package.json
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/Table/Internal/TableRow.vue
  packages/vue3/src/components/ToastContainer/ToastContainer.vue
  packages/vue3/src/helpers/index.ts
  packages/vue3/src/helpers/toast.ts
  packages/vue3/src/helpers/type.util.ts
  packages/vue3/src/utils/MyUtil.ts
  packages/vue3/src/utils/index.ts
  packages/vue3/src/utils/string.util.ts
Labels: ✅ Reviewed
