Repository youcan-shop/youcan-ui, pull requests merged in 2024-02, with the labels that each got.

#236 YSHOP2-1137-v2 : Rich text editor with froala
  .vscode/settings.json
  packages/vue3/package.json
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/_dev/index.ts
  packages/vue3/src/components/RichText/RichText.vue
  packages/vue3/src/components/RichText/extensions/Iframe.ts
  packages/vue3/src/components/RichText/extensions/textstyle.ts
  packages/vue3/src/components/RichText/handleDrop.ts
  packages/vue3/src/components/RichText/iconDefinition.ts
  packages/vue3/src/components/RichText/internal/Color.vue
  packages/vue3/src/components/RichText/internal/EmojiPicker.vue
  packages/vue3/src/components/RichText/internal/Table.vue
  packages/vue3/src/components/RichText/internal/Tooltip.vue
  packages/vue3/src/components/RichText/internal/emojis.ts
  packages/vue3/src/components/RichText/internal/swatches.ts
  packages/vue3/src/components/RichText/richTextConfig.ts
  packages/vue3/src/components/RichText/toolbar.ts
  packages/vue3/src/components/RichText/types.ts
  packages/vue3/src/froala.d.ts
  pnpm-lock.yaml
Labels: ✅ Reviewed

#257 Tag > Disabled state still allows user to edit
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/Tag/Tag.vue
Labels: 💻 Ready for review

#264 DARK dark-remove-ts-declaration
  packages/vue3/src/env.d.ts
  packages/vue3/tsconfig.json
Labels: 💻 Ready for review

#266 DARK: remove any trace of ToastContainer
  packages/vue3/package.json
  packages/vue3/src/components/ToastContainer/ToastContainer.vue
  packages/vue3/src/components/ToastContainer/internal/Toast.vue
  packages/vue3/src/components/ToastContainer/types.ts
  packages/vue3/src/components/index.ts
  packages/vue3/src/helpers/index.ts
  packages/vue3/src/types/index.ts
Labels: 💻 Ready for review

#268 Revert "DARK: remove any trace of ToastContainer"
  packages/vue3/package.json
  packages/vue3/src/components/ToastContainer/ToastContainer.vue
  packages/vue3/src/components/ToastContainer/internal/Toast.vue
  packages/vue3/src/components/ToastContainer/types.ts
  packages/vue3/src/components/index.ts
  packages/vue3/src/helpers/index.ts
  packages/vue3/src/types/index.ts
Labels: 💻 Ready for review

#271 Remove any trace of RichText TEMPORARILY
  .vscode/settings.json
  packages/vue3/package.json
  packages/vue3/src/_dev/index.ts
  packages/vue3/src/components/RichText/RichText.vue
  packages/vue3/src/components/RichText/iconDefinition.ts
  packages/vue3/src/components/RichText/richTextConfig.ts
  packages/vue3/src/components/RichText/types.ts
  packages/vue3/src/components/index.ts
  packages/vue3/src/froala.d.ts
  pnpm-lock.yaml
Labels: ✅ Reviewed

#272 DARK: Update ESLint config
  .eslintrc.js
  package.json
  pnpm-lock.yaml
Labels: 💻 Ready for review

#273 DARK: fix eslint
  .eslintrc.js
Labels: ✅ Reviewed

#275 YSHOP2-1366: Dropdown Tag component
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/Dropdown/DropdownList.vue
  packages/vue3/src/components/Dropdown/Internal/DropdownItem.vue
  packages/vue3/src/components/Tag/Tag.vue
  packages/vue3/src/components/Tag/types.ts
  packages/vue3/src/components/ToastContainer/ToastContainer.vue
Labels: ✅ Reviewed

#267 YSHOP2-1295: All components stories
  packages/vue3/src/components/ActionBar/ActionBar.stories.ts
  packages/vue3/src/components/Alert/Alert.stories.ts
  packages/vue3/src/components/Badge/Badge.stories.ts
  packages/vue3/src/components/Button/BaseButton.stories.ts
  packages/vue3/src/components/Button/Button.stories.ts
  packages/vue3/src/components/Button/PrimaryButton.stories.ts
  packages/vue3/src/components/Button/PrimaryDestructiveButton.stories.ts
  packages/vue3/src/components/Button/SecondaryButton.stories.ts
  packages/vue3/src/components/Button/SecondaryDestructiveButton.stories.ts
  packages/vue3/src/components/Button/TertiaryButton.stories.ts
  packages/vue3/src/components/Checkbox/Checkbox.stories.ts
  packages/vue3/src/components/Color/ColorInput.stories.ts
  packages/vue3/src/components/DateInput/DateInput.stories.ts
  packages/vue3/src/components/Divider/Divider.stories.ts
  packages/vue3/src/components/Draggable/Draggable.stories.ts
  packages/vue3/src/components/Draggable/DraggableItem.stories.ts
  packages/vue3/src/components/Drawer/Drawer.stories.ts
  packages/vue3/src/components/Dropdown/Dropdown.stories.ts
  packages/vue3/src/components/Dropdown/MultiselectDropdown.stories.ts
  packages/vue3/src/components/DropdownMenu/DropdownMenu.stories.ts
  packages/vue3/src/components/Increment/Increment.stories.ts
  packages/vue3/src/components/Input/DropdownPrefix.stories.ts
  packages/vue3/src/components/Input/Input.stories.ts
  packages/vue3/src/components/Loading/Loading.stories.ts
  packages/vue3/src/components/Modal/Modal.stories.ts
  packages/vue3/src/components/MultiSwitch/MultiSwitch.stories.ts
  packages/vue3/src/components/Note/Note.stories.ts
  packages/vue3/src/components/PaginationBar/PaginationBar.stories.ts
  packages/vue3/src/components/Percentage/Percentage.stories.ts
  packages/vue3/src/components/Percentage/Percentage.vue
  packages/vue3/src/components/Popover/Popover.stories.ts
  packages/vue3/src/components/Radio/Radio.stories.ts
  packages/vue3/src/components/RadioList/RadioList.stories.ts
  packages/vue3/src/components/Rating/Rating.stories.ts
  packages/vue3/src/components/Rating/RatingInput.vue
  packages/vue3/src/components/ResourcePicker/ResourcePicker.stories.ts
  packages/vue3/src/components/SettingsNav/SettingNav.stories.ts
  packages/vue3/src/components/SettingsNav/SettingNavItem.stories.ts
  packages/vue3/src/components/Sidebar/Sidebar.stories.ts
  packages/vue3/src/components/Sidebar/SidebarItem.stories.ts
  packages/vue3/src/components/Sidebar/SidebarSubitem.stories.ts
  packages/vue3/src/components/Skeleton/Skeleton.stories.ts
  packages/vue3/src/components/Slider/Slider.stories.ts
  packages/vue3/src/components/Spinner/Spinner.stories.ts
  packages/vue3/src/components/Status/EditableStatus.stories.ts
  packages/vue3/src/components/Status/StaticStatus.stories.ts
  packages/vue3/src/components/Table/Table.stories.ts
  packages/vue3/src/components/Tabs/Tab.stories.ts
  packages/vue3/src/components/Tabs/TabsBar.stories.ts
  packages/vue3/src/components/Tag/Tag.stories.ts
  packages/vue3/src/components/TextArea/TextArea.stories.ts
  packages/vue3/src/components/Thumbnail/Thumbnail.stories.ts
  packages/vue3/src/components/ToastContainer/Toast.stories.ts
  packages/vue3/src/components/Toggle/Toggle.stories.ts
  packages/vue3/src/components/Tooltip/Tooltip.stories.ts
  packages/vue3/src/components/Topbar/Topbar.stories.ts
  packages/vue3/src/components/Upload/FileInput.stories.ts
  packages/vue3/src/components/Upload/MediaInput.stories.ts
Labels: ✅ Reviewed

#274 Upload > Add support for videos
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/Upload/Internal/BaseFileInput.vue
  packages/vue3/src/components/Upload/UploadedFile.vue
  packages/vue3/src/components/Upload/UploadedMedia.vue
  packages/vue3/src/components/Upload/types.ts
  packages/vue3/src/components/Upload/utils.ts
Labels: ✅ Reviewed

#276 YSHOP2-1367: PaginationBar per page dropdown
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/Dropdown/types.ts
  packages/vue3/src/components/PaginationBar/PaginationBar.vue
  packages/vue3/src/components/PaginationBar/types.ts
Labels: 🛠 Requested changes

#280 YSHOP2-1368 : Added single date picker component
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/DateInput/SingleDateInput.vue
  packages/vue3/src/components/DateInput/SingleDatePicker.vue
  packages/vue3/src/components/DateInput/types.ts
  packages/vue3/src/components/index.ts
Labels: ✅ Reviewed

#281 UI-234: Dropdown > auto close on select
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/Dropdown/DropdownList.vue
  packages/vue3/src/components/Dropdown/Internal/DropdownItem.vue
  packages/vue3/src/components/Tag/Tag.vue
Labels: ✅ Reviewed

#284 UI 239: Slider > add range slider min max values
  packages/vue3/src/_dev/App.vue
  packages/vue3/src/components/Slider/Internal/Rail.vue
  packages/vue3/src/components/Slider/Internal/Tooltip.vue
  packages/vue3/src/components/Slider/Slider.vue
  packages/vue3/src/components/Slider/types.ts
  packages/vue3/src/types/index.ts
Labels: 💻 Ready for review
